// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzVhhTG-2SnqXkdg82IN0zK0h5JQqo-Ww',
    appId: '1:950090392084:web:cbc9483ea0f928886a3d01',
    messagingSenderId: '950090392084',
    projectId: 'food-home-84969',
    authDomain: 'food-home-84969.firebaseapp.com',
    storageBucket: 'food-home-84969.firebasestorage.app',
    measurementId: 'G-ZQWR28L7ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj0nxSwgL6ZrjhaFTB1-VFXMQ8BRxBDLQ',
    appId: '1:950090392084:android:074350c6932585086a3d01',
    messagingSenderId: '950090392084',
    projectId: 'food-home-84969',
    storageBucket: 'food-home-84969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC08R-IRriffWrFyBCLb00PLwSBb--h79o',
    appId: '1:950090392084:ios:d3a9baf3b412aac86a3d01',
    messagingSenderId: '950090392084',
    projectId: 'food-home-84969',
    storageBucket: 'food-home-84969.firebasestorage.app',
    iosClientId:
        '950090392084-6akuep3038t9sb82gbjc1l4ro13no1iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC08R-IRriffWrFyBCLb00PLwSBb--h79o',
    appId: '1:950090392084:ios:d3a9baf3b412aac86a3d01',
    messagingSenderId: '950090392084',
    projectId: 'food-home-84969',
    storageBucket: 'food-home-84969.firebasestorage.app',
    iosClientId:
        '950090392084-6akuep3038t9sb82gbjc1l4ro13no1iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodHomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzVhhTG-2SnqXkdg82IN0zK0h5JQqo-Ww',
    appId: '1:950090392084:web:e286ff6d006753a96a3d01',
    messagingSenderId: '950090392084',
    projectId: 'food-home-84969',
    authDomain: 'food-home-84969.firebaseapp.com',
    storageBucket: 'food-home-84969.firebasestorage.app',
    measurementId: 'G-S4V78H3F8P',
  );
}
